import { base44 } from 'npm:@base44/sdk@0.0.11';

const client = base44.createClient({ appId: '6992ac595576405eeacfea16' });

const members = [
  { display_name: "Gloria Tanner", username: "gloria_t", bio: "Born in the 50s, raised on Motown. I live and breathe classic soul music.", favorite_decade: "1960s", location: "Detroit, MI", followers_count: 312, following_count: 89, posts_count: 47, points: 1240, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=1" },
  { display_name: "Marcus Webb", username: "marcuswebb80", bio: "80s kid forever. Atari, cassette tapes, and Reaganomics — what a time to be alive.", favorite_decade: "1980s", location: "Chicago, IL", followers_count: 521, following_count: 203, posts_count: 83, points: 2890, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=3" },
  { display_name: "Sandra Okafor", username: "sandy_70s", bio: "Disco never died in my heart. Donna Summer is my queen.", favorite_decade: "1970s", location: "Atlanta, GA", followers_count: 198, following_count: 145, posts_count: 29, points: 870, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=5" },
  { display_name: "James Holloway", username: "jhollow_jazz", bio: "Jazz historian and vinyl collector. My record collection has over 2,000 LPs.", favorite_decade: "1950s", location: "New Orleans, LA", followers_count: 743, following_count: 312, posts_count: 156, points: 5420, membership_tier: "premium", is_verified: true, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=7" },
  { display_name: "Priya Sharma", username: "priya_90sgirl", bio: "90s baby. Spice Girls, NSYNC, and Tamagotchis defined my childhood.", favorite_decade: "1990s", location: "Houston, TX", followers_count: 467, following_count: 278, posts_count: 64, points: 1980, membership_tier: "free", is_verified: false, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=9" },
  { display_name: "Robert King", username: "bobking1940s", bio: "WWII history buff. My grandfather served and I honor his legacy every day.", favorite_decade: "1940s", location: "Philadelphia, PA", followers_count: 289, following_count: 112, posts_count: 38, points: 1340, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=11" },
  { display_name: "Latoya Simmons", username: "latoya_decade", bio: "Culture lover across all eras. From flappers to TikTok — history is my passion.", favorite_decade: "1920s", location: "Memphis, TN", followers_count: 834, following_count: 421, posts_count: 112, points: 3760, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=13" },
  { display_name: "Derek Fontaine", username: "derekf_punk", bio: "Punk rock saved my life in the 70s. The Ramones and Sex Pistols are timeless.", favorite_decade: "1970s", location: "Portland, OR", followers_count: 391, following_count: 167, posts_count: 55, points: 2100, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=15" },
  { display_name: "Carmen Rivera", username: "carmen_salsa", bio: "Miami girl. The 80s Latin music scene was electric and I was right in the middle of it.", favorite_decade: "1980s", location: "Miami, FL", followers_count: 612, following_count: 345, posts_count: 91, points: 3210, membership_tier: "premium", is_verified: false, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=16" },
  { display_name: "Theodore Banks", username: "theo_2000s", bio: "Y2K survivor. Remember when we thought the internet was just a fad? Good times.", favorite_decade: "2000s", location: "Seattle, WA", followers_count: 223, following_count: 189, posts_count: 41, points: 1120, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=17" },
  { display_name: "Nadia Petrov", username: "nadia_retro", bio: "Russian-American. Grew up between two worlds in the 90s. Huge fan of grunge.", favorite_decade: "1990s", location: "Denver, CO", followers_count: 445, following_count: 234, posts_count: 67, points: 2340, membership_tier: "free", is_verified: false, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=18" },
  { display_name: "Earl Washington", username: "earl_blues", bio: "Chicago blues runs in my blood. BB King, Muddy Waters — legends forever.", favorite_decade: "1960s", location: "Chicago, IL", followers_count: 567, following_count: 198, posts_count: 88, points: 3120, membership_tier: "premium", is_verified: true, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=19" },
  { display_name: "Melissa Grant", username: "melissa_vintage", bio: "Vintage fashion addict. I only wear clothes from before 1985. No exceptions.", favorite_decade: "1950s", location: "Nashville, TN", followers_count: 921, following_count: 512, posts_count: 143, points: 4890, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=20" },
  { display_name: "Tony Vasquez", username: "tonyv_hiphop", bio: "Hip hop head since 1988. Old school is the only school.", favorite_decade: "1990s", location: "New York, NY", followers_count: 1243, following_count: 678, posts_count: 201, points: 7650, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=21" },
  { display_name: "Helen Crawford", username: "helen_swing", bio: "My parents met at a swing dance in 1942. I carry their love of music with me.", favorite_decade: "1940s", location: "Kansas City, MO", followers_count: 178, following_count: 94, posts_count: 22, points: 780, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=22" },
  { display_name: "Andre Mitchell", username: "dre_funk", bio: "Parliament-Funkadelic changed my life. George Clinton is a genius.", favorite_decade: "1970s", location: "Oakland, CA", followers_count: 489, following_count: 267, posts_count: 74, points: 2670, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=23" },
  { display_name: "Rachel Kim", username: "rachelkim_pop", bio: "K-pop brought me to eDecades but now I'm obsessed with 90s American pop too.", favorite_decade: "2010s", location: "Los Angeles, CA", followers_count: 2341, following_count: 1023, posts_count: 312, points: 9870, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=24" },
  { display_name: "Bill Kowalski", username: "bill_polka", bio: "Polish-American, grew up in the 50s. Polka on Saturdays, baseball on Sundays.", favorite_decade: "1950s", location: "Cleveland, OH", followers_count: 134, following_count: 78, posts_count: 19, points: 540, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=25" },
  { display_name: "Jasmine Cole", username: "jasmine_soul", bio: "Neo-soul meets classic R&B in everything I do. Erykah Badu is my spirit animal.", favorite_decade: "2000s", location: "Baltimore, MD", followers_count: 678, following_count: 389, posts_count: 97, points: 3450, membership_tier: "premium", is_verified: false, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=26" },
  { display_name: "Frank Deluca", username: "frank_rocknroll", bio: "Elvis is the king. Period. End of story. Do not @ me.", favorite_decade: "1950s", location: "Memphis, TN", followers_count: 567, following_count: 212, posts_count: 88, points: 3120, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=27" },
  { display_name: "Aisha Williams", username: "aisha_afrobeat", bio: "Connecting African roots to American music history. Fela Kuti to Beyoncé.", favorite_decade: "1970s", location: "Washington, DC", followers_count: 892, following_count: 456, posts_count: 134, points: 4560, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=28" },
  { display_name: "Craig Hoffman", username: "craigh_metal", bio: "Heavy metal for life. Sabbath, Maiden, Metallica — the holy trinity.", favorite_decade: "1980s", location: "Birmingham, AL", followers_count: 423, following_count: 187, posts_count: 61, points: 2210, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=29" },
  { display_name: "Dorothy Hughes", username: "dot_flapper", bio: "My grandmother was a real flapper! I collect 1920s memorabilia in her honor.", favorite_decade: "1920s", location: "Charleston, SC", followers_count: 312, following_count: 143, posts_count: 48, points: 1780, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=30" },
  { display_name: "Marcus Chen", username: "marcus_techwiz", bio: "Software engineer by day, 90s tech nostalgia nerd by night. RIP Windows 95.", favorite_decade: "1990s", location: "San Francisco, CA", followers_count: 1089, following_count: 567, posts_count: 178, points: 6230, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=31" },
  { display_name: "Brenda Foster", username: "brenda_motown", bio: "Grew up in Detroit during the Motown golden age. I have stories you wouldn't believe.", favorite_decade: "1960s", location: "Detroit, MI", followers_count: 456, following_count: 234, posts_count: 72, points: 2890, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=32" },
  { display_name: "Kevin Osei", username: "kevin_ghana90s", bio: "Born in Ghana, moved to the US in 98. Both cultures shaped who I am.", favorite_decade: "1990s", location: "Minneapolis, MN", followers_count: 334, following_count: 201, posts_count: 53, points: 1890, membership_tier: "free", is_verified: false, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=33" },
  { display_name: "Linda Park", username: "lindapark_art", bio: "Art history professor. The 1960s counterculture art movement changed everything.", favorite_decade: "1960s", location: "Boston, MA", followers_count: 789, following_count: 345, posts_count: 124, points: 4320, membership_tier: "premium", is_verified: true, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=34" },
  { display_name: "Samuel Brooks", username: "sam_gospel", bio: "Gospel music historian. From the 1930s spirituals to modern praise — I know it all.", favorite_decade: "1930s", location: "Jackson, MS", followers_count: 267, following_count: 145, posts_count: 44, points: 1560, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=35" },
  { display_name: "Vanessa Torres", username: "vanessa_mambo", bio: "Cuban-American. The 1950s Havana music scene was the greatest in the world.", favorite_decade: "1950s", location: "Tampa, FL", followers_count: 398, following_count: 212, posts_count: 67, points: 2340, membership_tier: "free", is_verified: false, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=36" },
  { display_name: "Owen Fitzgerald", username: "owen_beatles", bio: "Saw The Beatles live at Shea Stadium in 1965. Greatest night of my life.", favorite_decade: "1960s", location: "New York, NY", followers_count: 1456, following_count: 678, posts_count: 234, points: 8900, membership_tier: "premium", is_verified: true, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=37" },
  { display_name: "Zoe Lambert", username: "zoe_indie", bio: "Indie music and film buff. The 2000s underground scene was chef's kiss.", favorite_decade: "2000s", location: "Austin, TX", followers_count: 534, following_count: 312, posts_count: 89, points: 3120, membership_tier: "free", is_verified: false, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=38" },
  { display_name: "Clarence Dupree", username: "clar_jazz2", bio: "Retired music teacher. 40 years of teaching kids to love jazz.", favorite_decade: "1940s", location: "New Orleans, LA", followers_count: 189, following_count: 98, posts_count: 31, points: 1120, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=39" },
  { display_name: "Monica Reyes", username: "moni_telenovela", bio: "Telenovelas and Latin pop from the 90s — my entire personality.", favorite_decade: "1990s", location: "San Antonio, TX", followers_count: 712, following_count: 389, posts_count: 108, points: 3780, membership_tier: "premium", is_verified: false, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=40" },
  { display_name: "Harold Stone", username: "harold_bigband", bio: "Big band era was the peak of American music. Nothing since has come close.", favorite_decade: "1940s", location: "Cincinnati, OH", followers_count: 145, following_count: 87, posts_count: 24, points: 890, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=41" },
  { display_name: "Tiffany Nguyen", username: "tiff_y2k", bio: "Y2K fashion is making a comeback and I was ahead of the curve the whole time.", favorite_decade: "2000s", location: "San Jose, CA", followers_count: 1678, following_count: 892, posts_count: 267, points: 8450, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=42" },
  { display_name: "Darnell Scott", username: "darnell_rap", bio: "Hip hop purist. 1993 was the greatest year in rap history. Fight me.", favorite_decade: "1990s", location: "Compton, CA", followers_count: 2134, following_count: 1012, posts_count: 345, points: 11200, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=43" },
  { display_name: "Eleanor Walsh", username: "eleanor_suffrage", bio: "Feminist historian specializing in the 1910s and 20s suffrage movement.", favorite_decade: "1920s", location: "Providence, RI", followers_count: 456, following_count: 234, posts_count: 78, points: 2890, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=44" },
  { display_name: "Patrick O'Brien", username: "pat_irishpub", bio: "Irish-American. Traditional music meets 70s rock in my vinyl collection.", favorite_decade: "1970s", location: "Boston, MA", followers_count: 289, following_count: 167, posts_count: 45, points: 1670, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=45" },
  { display_name: "Keisha Malone", username: "keisha_rnb", bio: "90s and 2000s R&B is my religion. Aaliyah forever.", favorite_decade: "2000s", location: "Charlotte, NC", followers_count: 1234, following_count: 678, posts_count: 198, points: 6780, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=46" },
  { display_name: "Victor Huang", username: "victor_martial", bio: "Bruce Lee fan since the 70s. Martial arts films changed cinema forever.", favorite_decade: "1970s", location: "Los Angeles, CA", followers_count: 567, following_count: 289, posts_count: 91, points: 3340, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=47" },
  { display_name: "Grace Jefferson", username: "grace_harlem", bio: "Harlem Renaissance is my passion. Langston Hughes changed American literature.", favorite_decade: "1930s", location: "Harlem, NY", followers_count: 678, following_count: 312, posts_count: 112, points: 4120, membership_tier: "premium", is_verified: true, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=48" },
  { display_name: "Scott Bradley", username: "scottb_grunge", bio: "Nirvana and Pearl Jam defined my entire high school experience. Class of 94.", favorite_decade: "1990s", location: "Seattle, WA", followers_count: 892, following_count: 445, posts_count: 145, points: 5230, membership_tier: "premium", is_verified: false, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=49" },
  { display_name: "Diane Monroe", username: "diane_oldschool", bio: "Old school everything. If it was made after 2000 I probably don't know it.", favorite_decade: "1980s", location: "Louisville, KY", followers_count: 334, following_count: 178, posts_count: 56, points: 2010, membership_tier: "free", is_verified: false, is_online: false, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=50" },
  { display_name: "Anthony Kittles", username: "anthonykittles", bio: "Founder of eDecades — connecting generations through the magic of nostalgia. 🎶", favorite_decade: "1990s", location: "Irving, TX", followers_count: 3421, following_count: 512, posts_count: 456, points: 25000, membership_tier: "premium", is_verified: true, is_online: true, account_status: "active", onboarding_completed: true, avatar_url: "https://i.pravatar.cc/150?img=52", profile_title: "Founder & CEO", badges: ["founder", "verified", "top_contributor"] }
];

export default async function handler(req: Request) {
  try {
    const results = [];
    for (const member of members) {
      const record = await client.asServiceRole.entities.UserProfile.create(member);
      results.push(record.id);
    }
    return new Response(JSON.stringify({ success: true, created: results.length, ids: results }), {
      headers: { 'Content-Type': 'application/json' }
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}
