export default async function sendDailyOpsEmail(req: Request) {
  const body = await req.json().catch(() => ({}));
  const { email } = body;

  if (!email) {
    return new Response(JSON.stringify({ error: "Email required" }), { status: 400 });
  }

  try {
    // Use Base44's built-in email service via Resend
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${Deno.env.get("RESEND_API_KEY")}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "noreply@base44.com",
        to: email,
        subject: "📋 Daily Operations Brief — May 10, 2026",
        html: `<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #333d4d; color: #d4956e; padding: 20px; border-radius: 8px; text-align: center; }
        h2 { color: #333d4d; margin-top: 30px; border-bottom: 3px solid #d4956e; padding-bottom: 10px; }
        .task-box { background: #f5f5f5; padding: 15px; margin: 10px 0; border-left: 4px solid #d4956e; border-radius: 4px; }
        .task-owner { font-weight: bold; color: #d4956e; font-size: 12px; }
        .task-title { font-weight: bold; margin: 5px 0; }
        .task-notes { font-size: 14px; color: #666; margin: 8px 0; }
        .tip { background: #fff3cd; padding: 12px; margin: 15px 0; border-radius: 4px; border-left: 4px solid #ffc107; }
        .status-empty { text-align: center; color: #999; padding: 30px; }
        a { color: #d4956e; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📋 Daily Operations Brief</h1>
            <p>Sunday, May 10, 2026 — 8:00 AM Central</p>
        </div>

        <h2>Current Status</h2>
        <div class="status-empty">
            <p>✅ No pending daily tasks in the tracker.</p>
            <p>The OpsTracker is currently empty. Add tasks using the admin panel or by messaging Antonio.</p>
        </div>

        <h2>Recent Automations (Last 24 Hours)</h2>
        <div class="task-box">
            <div class="task-owner">🤖 ANTONIO (Automated)</div>
            <div class="task-title">eDecades Daily Social Auto-Post</div>
            <div class="task-notes">✅ Ran 3x — Posted to LinkedIn, Pinterest, and TikTok</div>
        </div>
        <div class="task-box">
            <div class="task-owner">🤖 ANTONIO (Automated)</div>
            <div class="task-title">Affiliate Reply Monitor</div>
            <div class="task-notes">✅ Ran 2x — Checked for GoodRx, Blink Health, Mark Cuban Cost Plus Drugs replies</div>
        </div>

        <h2>Active Projects</h2>
        <div class="task-box">
            <div class="task-owner">🔄 IN PROGRESS</div>
            <div class="task-title">eDecades Migration to Vercel</div>
            <div class="task-notes">Deployed on Vercel via GitHub (Mecko1293/edecades). DNS propagation in progress after nameserver switch on 2026-05-10.</div>
        </div>
        <div class="task-box">
            <div class="task-owner">🔄 IN PROGRESS</div>
            <div class="task-title">CheapMedz Affiliate Outreach</div>
            <div class="task-notes">Draft ready to send to: GoodRx, Blink Health, Mark Cuban Cost Plus Drugs, Amazon Pharmacy, RxSpark</div>
        </div>

        <div class="tip">
            <strong>💡 Tip:</strong> To add daily, weekly, or monthly tasks, open the <a href="https://antonio-major-help-app.base44.app/eDecadesDailyTracker">eDecades Daily Tracker</a> and create new entries. Tasks appear here the next morning.
        </div>

        <div class="tip">
            <strong>🔗 Quick Links:</strong><br>
            • <a href="https://app.base44.com">Base44 App Builder</a><br>
            • <a href="https://antonio-major-help-app.base44.app/KingXcelPanel">King Xcel Control Hub</a><br>
            • <a href="https://github.com/Mecko1293/edecades">eDecades GitHub Repo</a><br>
            • <a href="https://vercel.com">Vercel Dashboard</a>
        </div>

        <p style="color: #999; font-size: 12px; margin-top: 40px;">
            This email was generated by Antonio at 8:00 AM Central. Next email tomorrow.
        </p>
    </div>
</body>
</html>`,
      }),
    });

    const result = await response.json();
    
    if (!response.ok) {
      return new Response(
        JSON.stringify({ error: "Failed to send email", details: result }),
        { status: 500 }
      );
    }

    return new Response(JSON.stringify({ success: true, messageId: result.id }), {
      status: 200,
    });
  } catch (error) {
    return new Response(
      JSON.stringify({ error: "Server error", message: error.message }),
      { status: 500 }
    );
  }
}
